### ISSUE TITLE
Pls, provide example for the rest of us

### ISSUE THREAD

**Issue by Asc2011** [disruptek/gully#1]
after consuming the help and help-syntax sections it remains unclear what parameters lead from the Input-example(s) to the Output-example(s) on the github-page ?
The options-section on github is bit inconsistent with what `gully -h` outputs. E.g. it has a `--syntax="#"` - Option ? Maybe this is the one that actually inserts '#' into the document ?
  
Really, i tried, but well ... maybe i'll try par.

thx

**Comment by disruptek** [comment]
Sorry, this thing is WIP.  I got bored after getting to first base.

**Comment by Asc2011** [comment]
:) fair enough - what params brought you to first base and would you publish them to enable others to reach first base, too ?
regards, i'll close this now,,
